# <center>Laboratorium 1<br>Metody Numeryczne</center>

Sztefko Mateusz 407388

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [6]:
import main
import numpy as np
import math


[[ 4]
 [12]
 [52]]
[[-6]
 [-3]
 [ 4]]
[[  8]
 [ 15]
 [-26]]
[[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]]
[[  4. -20.  10.]
 [-35.  10.  13.]
 [ 16.  40.  -8.]]
[[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]]
[[19]
 [49]
 [ 5]]
[[-62 -67  50]]
None


Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [7]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)


Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.

In [8]:
def cylinder_area(r:float,h:float):
    if (r < 0) or (h < 0):
        return np.NaN
    
    else:
        result = (math.pi*(r)**2*h)
        
        return result

print(cylinder_area(2,3))
print(cylinder_area(0,3))
print(cylinder_area(2,0))
print(cylinder_area(0,0))
print(cylinder_area(-2,3))
print(cylinder_area(2,-3))


37.69911184307752
0.0
0.0
0.0
nan
nan


***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji *[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)* oraz *[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)*. Wypisz go i przeanalizuj otrzymane rezultaty.

In [9]:
V_1 = np.arange(2,5,0.2)

V_2 = np.linspace(2,5,16)

print(V_1)
print(V_2)

[2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6 4.8]
[2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6 4.8 5. ]


***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

In [10]:
def fib(n):
    
    list_of_Fib = []
    if not isinstance(n,int):
        return None
    elif n <= 0:
        return None
    elif n == 1:
        return [1]
    else:

        list_of_Fib.append(1)
        last, value = 0, 1
    
        for i in range(0, n-1):
            last, value = value, last + value
            list_of_Fib.append(float(value))

    array_of_Fib = np.array([list_of_Fib])
    return array_of_Fib
    

***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

In [12]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))

def matrix_calculations(a:float) -> tuple[np.array, np.array, float]:
    
    M:np.array = np.array([[a,1,-a], [0,1,1], [-a,a,1]])  

    Mdet:float = np.linalg.det(M)

    Minv:np.array = np.zeros(3) 
    if Mdet != 0:
        Minv:np.array = np.linalg.inv(M)
    else:
        Minv = np.NaN
    
    Mt:np.array = np.transpose(M)
    
    return Minv, Mt, Mdet
print(matrix_calculations(2))
print(matrix_calculations(1))
print(matrix_calculations(0))
print(matrix_calculations(-1))
print(matrix_calculations(-2))

Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]
(array([[ 0.125,  0.625, -0.375],
       [ 0.25 ,  0.25 ,  0.25 ],
       [-0.25 ,  0.75 , -0.25 ]]), array([[ 2,  0, -2],
       [ 1,  1,  2],
       [-2,  1,  1]]), -7.999999999999998)
(array([[ 0. ,  1. , -1. ],
       [ 0.5,  0. ,  0.5],
       [-0.5,  1. , -0.5]]), array([[ 1,  0, -1],
       [ 1,  1,  1],
       [-1,  1,  1]]), -2.0)
(nan, array([[0, 0, 0],
       [1, 1, 0],
       [0, 1, 1]]), 0.0)
(array([[-1. ,  1. , -0. ],
       [-0.5,  1. , -0.5],
       [ 0.5,  0. ,  0.5]]), array([[-1,  0,  1],
       [ 1,  1, -1],
       [ 1,  1,  1]]), -2.0)
(array([[-0.375,  0.625,  0.125],
       [-0.25 ,  0.75 , -0.25 ],
       [ 0.25 ,  0.25 ,  0.25 ]]), array([[-2,  0,  2],
       [ 1,  1, -2],
       [ 2,  1,  1]]), -7.999999999999998)


Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.

***Zadanie 5.***  
Stwórz w noataniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie


In [13]:
# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

def From_matrix():
    M = np.array([[3, 1, -2, 4],[0, 1, 1, 5],[-2, 1, 1, 6],[4, 3, 0, 1]])
    w1 = M[:,2]
    w2 = M[1,:]
    
    print(M[0,0])
    print(M[2,2])
    print(M[2,1])
    print(w1)
    print(w2)

print(From_matrix())

Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]
3
1
1
[-2  1  1  0]
[0 1 1 5]
None


Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

In [15]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))



print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

def custom_matrix(m:int, n:int):

    if (m > 0) and isinstance(m, int) and (n > 0) and isinstance(n, int):
        
        Matrix = np.zeros((m, n))
        r_index:int = 0
        c_index:int = 0     
        
        for i in range(n):
            for j in range(m):

                if r_index > c_index:
                    Matrix[r_index, c_index]= r_index

                else:
                    Matrix[r_index, c_index]= c_index

                r_index += 1
            r_index = 0
            c_index += 1       
        return Matrix

    else:
        return None
m = np.random.randint(3, 7)
n = np.random.randint(3, 7)
print(custom_matrix(m, n))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]
[[0. 1. 2.]
 [1. 1. 2.]
 [2. 2. 2.]]


***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

In [17]:
def Task7_8():

    v1:np.array = np.array([[1],[3],[13]])
    v2:np.array = np.array([[8],[5],[-2]])

    v_4v1:np.array = np.dot(4, v1)
    v_v2_add_vector:np.array = np.add(-v2, [[2],[2],[2]])
    v_v1_cauchy_v2:np.array = np.dot(v1, np.transpose(v2))
    v_v1_hadamard_v2:np.array = np.multiply(v1, v2)



    print(v_4v1)
    print(v_v2_add_vector)
    print(v_v1_cauchy_v2)
    print(v_v1_hadamard_v2)


    M1 = np.array([[1,-7,3],[-12,3,4],[5,13,-3]])

    Matrix_3M1 = np.dot(3, M1)
    Matrix_3M1_add_onematrix = np.add(np.dot(3, M1), np.ones(3))
    Matrix_M1transpose = np.transpose(M1)
    Matrix_M1v1 = np.dot(M1, v1)
    Matrix_v1transposeM1 = np.dot(np.transpose(v2), M1)

    print(Matrix_3M1)
    print(Matrix_3M1_add_onematrix)
    print(Matrix_M1transpose)
    print(Matrix_M1v1)
    print(Matrix_v1transposeM1)


print(Task7_8())

[[ 4]
 [12]
 [52]]
[[-6]
 [-3]
 [ 4]]
[[  8   5  -2]
 [ 24  15  -6]
 [104  65 -26]]
[[  8]
 [ 15]
 [-26]]
[[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]]
[[  4. -20.  10.]
 [-35.  10.  13.]
 [ 16.  40.  -8.]]
[[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]]
[[19]
 [49]
 [ 5]]
[[-62 -67  50]]
None


Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)

Wnioski:

-W pierwszym zadaniu najważniejsze było postawienie prawidłowych warunków zadziałania funkcji. Dodatkowo konieczne było zaimportowanie biblioteki math aby uzyskac wartość Pi.
-W drugim zadaniu należało zaimportować bibliotekę numpy a następnie przy pomocy funkcji arange oraz linspace wygenerować dwa wektory. Powyżej przedstawiłem dwa takie same wektory wygenerowane przez te dwie funkcje. Funkcje te są bardzo podobne do siebie, zarówno w jednej jak i w drugiej jako dwa pierwsze argumenty przedstawiamy wartości początkową i końcową. Różnią się natomiast trzecim argumentem. W funkcji arange argument ten reprezentuje krok o jaki wartości się zmieniają, natomiast w funkcji linspace jest to długość jaką ma mieć nasz wektor.
-W zadaniu trzecim napisana została funkcja wypisująca elementy ciągu Fibonaciego. Funkcja ta jest napisana w sposób iteracyjny.
Dodatkowo na początku programu zostały zawartę warunki: gdy liczba nie bedzie liczbą całkowitą lub będzie liczbą całkowitą mniejszą bądź równą 0 funkcja zwróci wartość None.
-W zadaniu czwartym głównym zadaniem było zapoznanie się z funkcjami operacji na macierzach (linalg, transpose) oraz urzyć ich do obliczenia wskazanych w zadaniu elementów 
-Zadanie piąte polegało na stworzeniu podanej macierzy a następnie wypisaniu z niej konkretnych elementów, wiersz oraz kolumne. Ważne aby zwrócić uwagę na indeksowanie gdyż odbywa się ono od 0
-W zadaniu szóstym najpierw stworzona została macierz z elementami zerowymi, a nastepnie przy pomocy dwóch pętli for (jedna zagnieżdżona w drugiej) uzupełniamy macierz zgodnie z treścią zadania. Dodatkowo na początku funkcji stosujemy zabezpeiczenie które akurat w naszym przypadku (przy wykorzystaniu funkcji randint) jest zawsze spełnione, jednak zabezpieczenie to jest wymagane aby przejsć test działania programy.
-Zadanie siódme oraz ósme są do siebie bardzo podobne. W siódmym wykonujemy działania na wektorach natomiast w ósmym na macierzy. Podczas robienia punktu siedem miałem problem z mnożeniem Cauhy'ego jednak wkońcu zorientowałem się, że oczywiście są to dwa wektory a wiec aby dokonać jakiego kolwiek mnożenia musimy jeden z nich przetransponowac. W innym wypadku program wyrzuca nam błąd.  